import { DecimalPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { environment } from '../../../../environments/environment';
import { Project, Unit } from '../../../Core/Models/api.models';
import { ProjectsService } from '../../../Core/Services/projects.service';
import { SeoService } from '../../../Core/Services/seo.service';
import { UnitsService } from '../../../Core/Services/units.service';
import { TranslationService } from '../../../Core/I18n/translation.service';
import { TranslatePipe } from '../../../Shared/Pipes/translate.pipe';
@Component({selector:'app-project-details',imports:[DecimalPipe,RouterLink,TranslatePipe],template:`<section class="section"><div class="container">@if(project();as p){<a class="eyebrow" routerLink="/projects">→ {{'backProjects'|t}}</a><div class="detail"><div class="image"><img [src]="image()" width="800" height="580" [alt]="p.name"></div><article><p class="eyebrow">{{p.developerName}}</p><h1>{{p.name}}</h1><p class="muted">⌖ {{p.cityName}}، {{p.governorateName}}</p><p>{{p.description}}</p><div class="facts"><div><small>{{'startsFrom'|t}}</small><strong>{{p.startingPrice|number:'1.0-0'}} {{'egp'|t}}</strong></div><div><small>{{'units'|t}}</small><strong>{{p.unitsCount}}</strong></div><div><small>{{'status'|t}}</small><strong>{{status(p.status)}}</strong></div></div><a class="btn btn-gold" href="tel:+201000000000">{{'requestDetails'|t}}</a></article></div><div class="section-heading units-head"><div><p class="eyebrow">{{'insideProject'|t}}</p><h2>{{'availableUnits'|t}}</h2></div></div><div class="units">@for(u of units();track u.id){<article><h3>{{u.title||u.type}}</h3><p class="muted">{{u.area}} {{i18n.locale()==='ar'?'م²':'m²'}} · {{u.numberOfBedrooms||0}} {{'rooms'|t}}</p><strong>{{u.price|number:'1.0-0'}} {{'egp'|t}}</strong></article>}</div>}@else{<div class="empty-state">{{'loading'|t}}</div>}</div></section>`,styles:[`.detail{display:grid;grid-template-columns:1.15fr .85fr;gap:4rem;align-items:center;margin-top:2rem}.image{overflow:hidden;aspect-ratio:4/3;border:1px solid var(--color-border);border-radius:2rem}.image img{width:100%;height:100%;object-fit:cover}.detail h1{font-size:clamp(2.5rem,6vw,4.8rem);line-height:1.08;margin:.5rem 0}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem;margin:2rem 0}.facts div,.units article{display:grid;padding:1rem;border:1px solid var(--color-border);border-radius:1rem;background:var(--card-bg)}.facts small{color:var(--color-muted)}.facts strong,.units strong{color:var(--color-primary)}.units-head{margin-top:5rem}.units{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.units h3{margin:0}@media(max-width:820px){.detail{grid-template-columns:1fr;gap:2rem}.units{grid-template-columns:1fr}}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class ProjectDetailsComponent { private id=Number(inject(ActivatedRoute).snapshot.paramMap.get('id')); readonly i18n=inject(TranslationService); readonly project=signal<Project|null>(null); readonly units=signal<Unit[]>([]); readonly image=computed(()=>{const p=this.project()?.images?.[0];return p?(p.startsWith('http')?p:`${environment.apiOrigin}/${p.replace(/^\//,'')}`):'assets/brand/kemit-logo.jpeg'}); constructor(){const seo=inject(SeoService);inject(ProjectsService).getById(this.id).subscribe({next:p=>{this.project.set(p);seo.update(p.name,p.description||this.i18n.translate('propertyDetails'),`/projects/${p.id}`)}});inject(UnitsService).getAll(this.id).subscribe({next:r=>this.units.set(r.data),error:()=>{}})} status(value:unknown){const key=String(value).toLowerCase();return this.i18n.translate(key)||String(value);}}
