import { DatePipe, DecimalPipe, DOCUMENT } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { TranslationService } from '../../../Core/I18n/translation.service';
import { Project, Unit } from '../../../Core/Models/api.models';
import { ProjectsService } from '../../../Core/Services/projects.service';
import { SeoService } from '../../../Core/Services/seo.service';
import { UnitsService } from '../../../Core/Services/units.service';
import { NotificationService } from '../../../Core/Services/notification.service';
import { AuthService } from '../../../Core/Services/auth.service';
import { FavoritesService } from '../../../Core/Services/favorites.service';
import { LocationNamePipe } from '../../../Shared/Pipes/location-name.pipe';

@Component({
  selector: 'app-unit-details',
  imports: [DatePipe, DecimalPipe, RouterLink, LocationNamePipe],
  template: `
    <section class="unit-page"><div class="container">
      @if (unit(); as u) {
        <nav class="breadcrumbs"><a routerLink="/projects">{{ text('المشروعات','Projects') }}</a><span>‹</span><a [routerLink]="['/projects', projectId]">{{ u.projectName }}</a><span>‹</span><span>{{ title() }}</span></nav>
        <div class="gallery"><img [src]="mainImage()" [alt]="title()"><span class="photo-count">{{ selectedImage()+1 }} / {{ images().length }}</span>
          @if(images().length>1){<button class="arrow previous" type="button" (click)="previousImage()">‹</button><button class="arrow next" type="button" (click)="nextImage()">›</button><div class="dots">@for(image of images();track image;let i=$index){<button type="button" [class.active]="selectedImage()===i" (click)="selectedImage.set(i)"></button>}</div>}
        </div>
        <div class="page-grid"><main>
          <div class="headline"><div><span class="type-badge">{{ activityLabel() }}</span><span>{{ typeLabel() }}</span><span class="status">{{ statusLabel() }}</span></div><button class="favorite" type="button" [class.selected]="favorite()" (click)="toggleFavorite()" [attr.aria-label]="favorite()?text('إزالة من المفضلة','Remove from favorites'):text('إضافة للمفضلة','Add to favorites')"><svg viewBox="0 0 24 24"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg><span>{{favorite()?text('محفوظ','Saved'):text('حفظ','Save')}}</span></button></div>
          <h1>{{ title() }}</h1>
          <div class="location"><span>⌖ {{ project()?.cityName | locationName }}، {{ project()?.governorateName | locationName }}</span>@if(mapUrl();as url){<a [href]="url" target="_blank" rel="noopener">⌖ {{ text('عرض على الخريطة','View on map') }}</a>}<div class="share-wrap"><button class="share-trigger" type="button" (click)="shareOpen.update(value=>!value)" [attr.aria-expanded]="shareOpen()"><svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.6-4.5M8.2 13.2l7.6 4.5"/></svg>{{text('مشاركة الوحدة','Share unit')}}</button>@if(shareOpen()){<div class="share-menu"><a [href]="whatsappShareUrl()" target="_blank" rel="noopener" (click)="shareOpen.set(false)"><i class="whatsapp">◉</i>{{text('واتساب','WhatsApp')}}</a><a [href]="facebookShareUrl()" target="_blank" rel="noopener" (click)="shareOpen.set(false)"><i class="facebook">f</i>{{text('فيسبوك','Facebook')}}</a><button type="button" (click)="copyUnitLink()"><i class="copy">▣</i>{{text('نسخ الرابط','Copy link')}}</button></div>}</div></div>
          <strong class="price">{{ u.price | number:'1.0-0' }} <small>{{ text('جنيه','EGP') }}</small></strong>
          <section class="details"><h2>{{ text('تفاصيل الوحدة','Unit details') }}</h2><div class="details-grid">
            <div><i>⌂</i><span>{{ text('نوع النشاط','Activity') }}</span><b>{{ activityLabel() }}</b></div><div><i>◆</i><span>{{ text('نوع الوحدة','Unit type') }}</span><b>{{ typeLabel() }}</b></div>
            <div><i>✓</i><span>{{ text('الحالة','Status') }}</span><b>{{ statusLabel() }}</b></div><div><i>▰</i><span>{{ text('المساحة','Area') }}</span><b>{{ u.area }} {{ text('م²','sqm') }}</b></div>
            <div><i>▱</i><span>{{ text('عدد الغرف','Number of rooms') }}</span><b>{{ u.numberOfBedrooms || 0 }}</b></div><div><i>♨</i><span>{{ text('الحمامات','Bathrooms') }}</span><b>{{ u.numberOfBathrooms || 0 }}</b></div>
            @if(u.floorNumber!=null){<div><i>≡</i><span>{{ text('رقم الطابق','Floor') }}</span><b>{{ u.floorNumber }}</b></div>}@if(u.numberOfFloors){<div><i>▤</i><span>{{ text('عدد الطوابق','Floors') }}</span><b>{{ u.numberOfFloors }}</b></div>}
            <div><i>◷</i><span>{{ text('تاريخ الإضافة','Added on') }}</span><b>{{ u.createdAt | date:'d MMMM y':'':dateLocale() }}</b></div>
          </div></section>
          <section class="description"><p>{{ text('عن الوحدة','About the unit') }}</p><h2>{{ text('وصف الوحدة','Unit description') }}</h2><div>{{ u.description || text('لا يوجد وصف متاح لهذه الوحدة.','No description is available for this unit.') }}</div></section>
        </main><aside><div class="summary-card">
          @if(project();as p){<div class="identity-row"><a class="developer" [routerLink]="['/developers',p.developerId]"><img [src]="developerLogo()" [alt]="p.developerName"><div><small>{{ text('المطور العقاري','Developer') }}</small><strong>{{ p.developerName }}</strong></div></a><a class="project-identity" [routerLink]="['/projects',p.id]"><small>{{ text('اسم المشروع','Project name') }}</small><strong>{{ p.name }}</strong></a></div>}
          <div class="price-box"><span>{{ text('سعر الوحدة','Unit price') }}</span><b>{{ u.price | number:'1.0-0' }} {{ text('جنيه','EGP') }}</b></div>
          @if(u.downPayment || u.installmentYears || u.monthlyInstallment){<div class="payment"><h3>{{ text('تفاصيل التقسيط','Installment details') }}</h3>@if(u.downPayment){<div><span>{{ text('المقدم','Down payment') }}</span><b>{{ u.downPayment|number:'1.0-0' }} {{text('جنيه','EGP')}}</b></div>}@if(u.installmentYears){<div><span>{{ text('مدة التقسيط','Duration') }}</span><b>{{u.installmentYears}} {{text('سنوات','years')}}</b></div>}@if(u.monthlyInstallment){<div><span>{{ text('القسط الشهري','Monthly installment') }}</span><b>{{u.monthlyInstallment|number:'1.0-0'}} {{text('جنيه','EGP')}}</b></div>}</div>}
          <a class="project-button" [routerLink]="['/projects',projectId]">{{ text('عرض المشروع','View project') }}</a><small class="reference">{{ text('رقم الوحدة','Unit ID') }}: {{u.id}}</small>
        </div></aside></div>
      } @else if(loadFailed()){<div class="state"><strong>{{text('تعذر تحميل تفاصيل الوحدة','Could not load unit details')}}</strong><a routerLink="/projects">{{text('العودة للمشروعات','Back to projects')}}</a></div>} @else {<div class="state">{{text('جاري تحميل تفاصيل الوحدة...','Loading unit details...')}}</div>}
    </div></section>`,
  styles: [`
    .unit-page{min-height:100vh;padding:1.5rem 0 5rem;background:#f6f4ee;color:#19160f}.breadcrumbs{display:flex;align-items:center;gap:.5rem;margin-bottom:1rem;color:#777166;font-size:.76rem}.breadcrumbs a{color:#815c18;font-weight:800}.gallery{position:relative;height:min(55vw,540px);overflow:hidden;border-radius:22px;background:#171717}.gallery>img{width:100%;height:100%;object-fit:cover}.photo-count{position:absolute;inset-inline-end:1rem;bottom:1rem;padding:.45rem .75rem;border:1px solid #ffffff45;border-radius:99px;background:#080808cf;color:#fff;font-size:.78rem;font-weight:800}.arrow{position:absolute;top:50%;display:grid;width:46px;height:64px;place-items:center;border:1px solid #ffffff55;border-radius:12px;background:#090909a8;color:#fff;font-size:2.5rem;cursor:pointer;transform:translateY(-50%)}.previous{inset-inline-start:1rem}.next{inset-inline-end:1rem}.dots{position:absolute;bottom:1.15rem;left:50%;display:flex;gap:.4rem;transform:translateX(-50%)}.dots button{width:8px;height:8px;padding:0;border:0;border-radius:50%;background:#ffffff80}.dots .active{width:22px;border-radius:99px;background:#e3b84f}
    .page-grid{display:grid;grid-template-columns:minmax(0,1fr) 350px;gap:3.5rem;margin-top:2rem}.headline{display:flex;align-items:center;justify-content:space-between}.headline>div{display:flex;align-items:center;gap:.7rem;color:#777166;font-size:.8rem}.type-badge,.status{padding:.3rem .7rem;border-radius:6px;background:#17140e;color:#f6d77e;font-size:.76rem;font-weight:800}h1{margin:.65rem 0 .25rem;font-size:clamp(1.8rem,4vw,2.8rem)}.location{display:flex;align-items:center;flex-wrap:wrap;gap:.7rem;color:#6e695f}.location>a,.share-trigger{display:inline-flex;align-items:center;gap:.4rem;padding:.48rem .75rem;border:1px solid #d1b66d;border-radius:8px;background:#fffaf0;color:#815c18;font:inherit;font-size:.78rem;font-weight:900;cursor:pointer}.share-trigger svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.7}.share-wrap{position:relative}.share-menu{position:absolute;z-index:15;top:calc(100% + .45rem);inset-inline-end:0;display:grid;width:180px;padding:.55rem;border:1px solid #ddd6c9;border-radius:12px;background:#fff;box-shadow:0 14px 35px #241d1225}.share-menu a,.share-menu button{display:flex;align-items:center;justify-content:flex-start;gap:.7rem;width:100%;padding:.65rem;border:0;border-radius:8px;background:transparent;color:#28231c;font:inherit;font-size:.78rem;font-weight:800;cursor:pointer}.share-menu a:hover,.share-menu button:hover{background:#f5f2eb}.share-menu i{display:grid;width:24px;height:24px;flex:0 0 auto;place-items:center;border-radius:50%;color:#fff;font-style:normal;font-weight:900}.share-menu .whatsapp{background:#20c76b}.share-menu .facebook{background:#287be0}.share-menu .copy{background:#92701f}.price{display:block;margin-top:1.2rem;color:#815c18;font-size:2rem}.price small{font-size:.85rem}.details,.description{margin-top:1.8rem;padding:1.8rem 0;border-top:1px solid #d9d5cc}.details h2,.description h2{margin:0 0 1.25rem}.details-grid{display:grid;grid-template-columns:1fr 1fr;gap:1.15rem 2.5rem}.details-grid div{display:grid;grid-template-columns:28px 1fr auto;align-items:center;gap:.6rem}.details-grid i{color:#a7781f;font-style:normal}.details-grid span{color:#777166;font-size:.82rem}.details-grid b{text-align:end;font-size:.86rem}.description>p{margin:0;color:#9a6e19}.description>div{color:#514d45;line-height:2;white-space:pre-line}
    aside{position:relative}.summary-card{position:sticky;top:92px;padding:1.25rem;border:1px solid #d9d4c9;border-radius:14px;background:#fff;box-shadow:0 12px 38px #2d271b18}.identity-row{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);align-items:center;gap:1rem;padding-bottom:1rem;border-bottom:1px solid #e2ded5}.developer{display:flex;align-items:center;min-width:0;gap:.8rem}.developer img{width:64px;height:64px;flex:0 0 auto;border:2px solid #e3b84f;border-radius:50%;object-fit:contain;background:#17140e}.developer div,.project-identity{display:grid;min-width:0}.developer small,.project-identity small,.price-box span,.payment span{color:#777166}.developer strong,.project-identity strong{overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.project-identity{gap:.25rem;padding-inline-start:1rem;border-inline-start:1px solid #e2ded5}.project-identity strong{color:#815c18}.developer:hover strong,.project-identity:hover strong{color:#a7781f}.price-box{display:grid;gap:.25rem;margin:1rem 0;padding:1rem;border-radius:10px;background:#f5f2eb;text-align:center}.price-box b{font-size:1.3rem}.payment{display:grid;gap:.75rem;padding-bottom:1rem}.payment h3{margin:.2rem 0}.payment div{display:flex;justify-content:space-between;gap:1rem;font-size:.78rem}.payment b{text-align:end}.project-button{display:block;padding:.8rem;border-radius:8px;background:#17140e;color:#f6d77e;text-align:center;font-weight:900}.reference{display:block;margin-top:1rem;color:#817b70;text-align:center}.state{display:grid;max-width:560px;gap:1rem;margin:5rem auto;padding:3rem;border:1px solid #d9d4c9;border-radius:14px;background:#fff;text-align:center}.state a{color:#815c18;font-weight:900}
    @media(max-width:900px){.page-grid{grid-template-columns:1fr;gap:1.5rem}.summary-card{position:static}}@media(max-width:620px){.unit-page{padding-top:1rem}.gallery{height:280px;border-radius:14px}.details-grid{grid-template-columns:1fr}.page-grid{margin-top:1.4rem}.arrow{width:38px;height:52px}}
    .favorite{display:flex;align-items:center;gap:.4rem;padding:.5rem .8rem;border:1px solid #d5d0c5;border-radius:8px;background:#fff;color:#19160f;font:inherit;cursor:pointer}.favorite svg{width:20px;height:20px;fill:transparent;stroke:#a7781f;stroke-width:1.8}.favorite.selected{border-color:#c99b35;color:#815c18}.favorite.selected svg{fill:#c99b35}
  `],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UnitDetailsComponent {
  private readonly route = inject(ActivatedRoute); private readonly i18n = inject(TranslationService); private readonly seo = inject(SeoService);
  private readonly document = inject(DOCUMENT); private readonly notices = inject(NotificationService); private readonly auth=inject(AuthService); private readonly favorites=inject(FavoritesService);
  readonly projectId = Number(this.route.snapshot.paramMap.get('projectId')); readonly unitId = Number(this.route.snapshot.paramMap.get('unitId'));
  readonly unit = signal<Unit|null>(null); readonly project = signal<Project|null>(null); readonly selectedImage=signal(0); readonly loadFailed=signal(false);
  readonly shareOpen=signal(false); readonly favorite=signal(false);
  readonly title=computed(()=>this.unit()?.title||this.typeLabel());
  readonly images=computed(()=>{const paths=this.unit()?.images?.length?this.unit()!.images:[''];return paths.map(p=>this.imageUrl(p)||'assets/brand/kemit-logo.jpeg');});
  readonly mainImage=computed(()=>this.images()[this.selectedImage()]||this.images()[0]);
  readonly developerLogo=computed(()=>this.imageUrl(this.project()?.developerLogoUrl||'')||'assets/brand/kemit-logo-128.png');
  readonly mapUrl=computed(()=>{const u=this.unit(),p=this.project();const lat=Number(u?.latitude??p?.latitude),lng=Number(u?.longitude??p?.longitude);return Number.isFinite(lat)&&Number.isFinite(lng)&&(u?.latitude!=null||p?.latitude!=null)?`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=16/${lat}/${lng}`:null;});
  constructor(){forkJoin({unit:inject(UnitsService).getById(this.projectId,this.unitId),project:inject(ProjectsService).getById(this.projectId)}).subscribe({next:({unit,project})=>{this.unit.set(unit);this.project.set(project);this.seo.update(unit.title||this.typeLabel(),unit.description||this.text('تفاصيل الوحدة العقارية','Real estate unit details'),`/projects/${this.projectId}/units/${unit.id}`);},error:()=>this.loadFailed.set(true)});if(this.auth.isAuthenticated())this.favorites.checkUnit(this.unitId).subscribe({next:r=>this.favorite.set(r.isFavorite),error:()=>{}});}
  text(ar:string,en:string){return this.i18n.locale()==='ar'?ar:en;} dateLocale(){return this.i18n.locale()==='ar'?'ar-EG':'en-US';}
  previousImage(){this.selectedImage.update(i=>(i-1+this.images().length)%this.images().length);} nextImage(){this.selectedImage.update(i=>(i+1)%this.images().length);}
  whatsappShareUrl(){return `https://wa.me/?text=${encodeURIComponent(`${this.title()} - ${this.document.location.href}`)}`;}
  facebookShareUrl(){return `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(this.document.location.href)}`;}
  async copyUnitLink(){const nav=this.document.defaultView?.navigator;if(nav?.clipboard){await nav.clipboard.writeText(this.document.location.href);this.notices.show(this.text('تم نسخ رابط الوحدة','Unit link copied'),'success');}this.shareOpen.set(false);}
  toggleFavorite(){if(!this.auth.isAuthenticated()){this.notices.show(this.text('سجّل الدخول لإضافة الوحدة إلى المفضلة.','Sign in to add this unit to favorites.'),'info');return;}const selected=this.favorite();(selected?this.favorites.removeUnit(this.unitId):this.favorites.addUnit(this.unitId)).subscribe(()=>{this.favorite.set(!selected);this.notices.show(selected?this.text('تمت إزالة الوحدة من المفضلة','Unit removed from favorites'):this.text('تمت إضافة الوحدة إلى المفضلة','Unit added to favorites'),'success',3500);});}
  activityLabel(){return this.label(this.unit()?.activityType,{Residential:this.text('سكني','Residential'),Commercial:this.text('تجاري','Commercial'),'0':this.text('سكني','Residential'),'1':this.text('تجاري','Commercial')});}
  statusLabel(){return this.label(this.unit()?.status,{Available:this.text('متاحة','Available'),Reserved:this.text('محجوزة','Reserved'),Sold:this.text('مباعة','Sold'),Unavailable:this.text('غير متاحة','Unavailable'),'1':this.text('متاحة','Available'),'2':this.text('محجوزة','Reserved'),'3':this.text('مباعة','Sold'),'4':this.text('غير متاحة','Unavailable')});}
  typeLabel(){return this.label(this.unit()?.type,{Apartment:this.text('شقة','Apartment'),Villa:this.text('فيلا','Villa'),Duplex:this.text('دوبلكس','Duplex'),House:this.text('منزل','House'),chalet:this.text('شاليه','Chalet'),Studio:this.text('استوديو','Studio'),HotelUnit:this.text('وحدة فندقية','Hotel unit'),Office:this.text('مكتب','Office'),MedicalClinic:this.text('عيادة طبية','Medical clinic'),CommercialBuilding:this.text('مبنى تجاري','Commercial building'),Warehouse:this.text('مخزن','Warehouse'),Factory:this.text('مصنع','Factory'),Garage:this.text('جراج','Garage'),RestaurantOrCafe:this.text('مطعم أو كافيه','Restaurant or cafe'),Land:this.text('أرض','Land'),Penthouse:this.text('بينت هاوس','Penthouse'),TownHouse:this.text('تاون هاوس','Town house'),TwinHouse:this.text('توين هاوس','Twin house')});}
  private imageUrl(path:string){return path?(path.startsWith('http')?path:`${environment.apiOrigin}/${path.replace(/^\//,'')}`):'';} private label(value:unknown,labels:Record<string,string>){return labels[String(value??'')]||String(value??'');}
}
