import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from '../../../Core/Services/auth.service';
import { NotificationService } from '../../../Core/Services/notification.service';
import { SeoService } from '../../../Core/Services/seo.service';
import { TranslationService } from '../../../Core/I18n/translation.service';
import { TranslatePipe } from '../../../Shared/Pipes/translate.pipe';
import { matchFields } from '../../../Shared/Validators/form.validators';
@Component({selector:'app-reset-password',imports:[ReactiveFormsModule,RouterLink,TranslatePipe],templateUrl:'./reset-password.component.html',styles:[`.password-field{position:relative}.password-field .form-control{padding-inline-end:3.2rem}.password-toggle{position:absolute;top:50%;inset-inline-end:.65rem;display:grid;width:36px;height:36px;place-items:center;transform:translateY(-50%);border:0;border-radius:50%;background:transparent;color:var(--color-muted);cursor:pointer}.password-toggle:hover,.password-toggle:focus-visible{background:rgba(227,184,79,.1);color:var(--color-primary)}.password-toggle svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8}.link-error{padding:1rem;border:1px solid #8c4141;border-radius:1rem;background:#2b1414;color:#ffd1d1}.account-email{padding:.75rem 1rem;border:1px solid var(--color-border);border-radius:var(--radius-sm);background:#0d0d0d;color:var(--gray-300);overflow-wrap:anywhere}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class ResetPasswordComponent { private fb=inject(FormBuilder);private route=inject(ActivatedRoute);private auth=inject(AuthService);private router=inject(Router);private notices=inject(NotificationService);private i18n=inject(TranslationService);private readonly email=this.route.snapshot.queryParamMap.get('email')?.trim()??'';private readonly token=this.route.snapshot.queryParamMap.get('token')??'';readonly submitting=signal(false);readonly requestFailed=signal(false);readonly showPassword=signal(false);readonly showConfirmPassword=signal(false);readonly invalidLink=!this.email||!this.token;readonly form=this.fb.nonNullable.group({email:[this.email,[Validators.required,Validators.email]],token:[this.token,Validators.required],newPassword:['',[Validators.required,Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&]).{8,}$/)]],confirmNewPassword:['',Validators.required]},{validators:matchFields('newPassword','confirmNewPassword')});constructor(){inject(SeoService).update('كلمة مرور جديدة','عين كلمة مرور جديدة لحساب كيميت.','/auth/reset-password')}togglePassword(){this.showPassword.update(value=>!value)}toggleConfirmPassword(){this.showConfirmPassword.update(value=>!value)}submit(){if(this.form.invalid||this.submitting()||this.invalidLink){this.form.markAllAsTouched();return}this.requestFailed.set(false);this.submitting.set(true);this.auth.resetPassword(this.form.getRawValue()).pipe(finalize(()=>this.submitting.set(false))).subscribe({next:()=>{this.notices.show(this.i18n.locale()==='ar'?'تم تحديث كلمة المرور. يمكنك تسجيل الدخول الآن.':'Password updated. You can now sign in.','success');void this.router.navigateByUrl('/auth/login')},error:()=>this.requestFailed.set(true)})}}
