import { DecimalPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { environment } from '../../../environments/environment';
import { Favorite, Unit } from '../../Core/Models/api.models';
import { FavoritesService } from '../../Core/Services/favorites.service';
import { NotificationService } from '../../Core/Services/notification.service';
import { SeoService } from '../../Core/Services/seo.service';
import { ListingCardComponent } from '../../Shared/Components/listing-card/listing-card.component';
import { TranslatePipe } from '../../Shared/Pipes/translate.pipe';
import { TranslationService } from '../../Core/I18n/translation.service';

@Component({selector:'app-favorites',imports:[ListingCardComponent,TranslatePipe,DecimalPipe,RouterLink],template:`
<section class="section"><div class="container"><p class="eyebrow">{{'yourChoices'|t}}</p><div class="section-heading"><div><h1>{{'favoriteProperties'|t}}</h1><p class="muted">{{'favoritesLead'|t}}</p></div></div>
@if(items().length){<h2>{{text('الإعلانات','Listings')}}</h2><div class="grid-cards">@for(item of items();track item.favoriteId){<app-listing-card [item]="item" kind="property" (favoriteChange)="onAdvertisementFavoriteChange($event)"/>}</div>}
@if(units().length){<h2 class="units-title">{{text('الوحدات','Units')}}</h2><div class="unit-grid">@for(unit of units();track unit.id){<a class="unit-card" [routerLink]="['/projects',unit.projectId,'units',unit.id]"><div class="image"><img [src]="unitImage(unit)" [alt]="unit.title||unit.projectName"><button type="button" (click)="removeUnit($event,unit.id)" [attr.aria-label]="text('إزالة من المفضلة','Remove from favorites')">♥</button></div><div class="body"><small>{{unit.projectName}}</small><h3>{{unit.title||unitTypeLabel(unit.type)}}</h3><div><span>{{unit.area}} {{text('م²','m²')}}</span><span>{{unit.numberOfBedrooms||0}} {{text('غرف','rooms')}}</span><span>{{unit.numberOfBathrooms||0}} {{text('حمام','bathrooms')}}</span></div><strong>{{unit.price|number:'1.0-0'}} {{text('جنيه','EGP')}}</strong></div></a>}</div>}
@if(!items().length&&!units().length){<div class="empty-state">{{'noFavorites'|t}}</div>}
</div></section>`,styles:[`.units-title{margin-top:3rem}.unit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.unit-card{display:block;overflow:hidden;border:1px solid var(--color-border);border-radius:14px;background:var(--card-bg);color:inherit;transition:.25s}.unit-card:hover{transform:translateY(-5px)}.image{position:relative;height:210px;background:#171717}.image img{width:100%;height:100%;object-fit:cover}.image button{position:absolute;top:.7rem;inset-inline-end:.7rem;width:40px;height:40px;border:1px solid #ffffff70;border-radius:50%;background:#090909bd;color:var(--color-primary);font-size:1.2rem;cursor:pointer}.body{padding:1rem}.body small{color:var(--color-primary)}.body h3{margin:.3rem 0 .8rem}.body>div{display:flex;flex-wrap:wrap;gap:.4rem}.body span{padding:.3rem .5rem;border-radius:6px;background:#ffffff0a;color:var(--color-muted);font-size:.7rem}.body strong{display:block;margin-top:1rem;color:var(--color-primary)}@media(max-width:900px){.unit-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.unit-grid{grid-template-columns:1fr}}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class FavoritesComponent{readonly items=signal<Favorite[]>([]);readonly units=signal<Unit[]>([]);private favorites=inject(FavoritesService);private notices=inject(NotificationService);private i18n=inject(TranslationService);constructor(){inject(SeoService).updateLocalized('المفضلة','Favorites','إعلاناتك ووحداتك المفضلة على كيميت.','Your favorite listings and units on Kemet.','/favorites');forkJoin({ads:this.favorites.getAll(),units:this.favorites.getUnits()}).subscribe({next:r=>{this.items.set(r.ads);this.units.set(r.units)},error:()=>{}})}text(arabic:string,english:string){return this.i18n.locale()==='ar'?arabic:english}unitTypeLabel(value:string){const labels:Record<string,[string,string]>={Apartment:['شقة','Apartment'],Villa:['فيلا','Villa'],Duplex:['دوبلكس','Duplex'],House:['منزل','House'],chalet:['شاليه','Chalet'],Studio:['استوديو','Studio'],HotelUnit:['وحدة فندقية','Hotel unit'],Office:['مكتب','Office'],CommercialStore:['محل تجاري','Commercial store'],MedicalClinic:['عيادة طبية','Medical clinic'],CommercialBuilding:['مبنى تجاري','Commercial building'],Warehouse:['مخزن','Warehouse'],Factory:['مصنع','Factory'],Garage:['جراج','Garage'],RestaurantOrCafe:['مطعم أو كافيه','Restaurant or cafe'],Land:['أرض','Land'],Penthouse:['بينت هاوس','Penthouse'],TownHouse:['تاون هاوس','Town house'],TwinHouse:['توين هاوس','Twin house']};const label=labels[value];return label?this.text(label[0],label[1]):value}unitImage(unit:Unit){const path=unit.images?.[0];return path?(path.startsWith('http')?path:`${environment.apiOrigin}/${path.replace(/^\//,'')}`):'assets/brand/kemit-logo.jpeg'}onAdvertisementFavoriteChange(event:{advertisementId:number;isFavorite:boolean}){if(!event.isFavorite)this.items.update(items=>items.filter(item=>item.advertisementId!==event.advertisementId))}removeUnit(event:Event,id:number){event.preventDefault();event.stopPropagation();this.favorites.removeUnit(id).subscribe(()=>{this.units.update(items=>items.filter(x=>x.id!==id));this.notices.show(this.text('تمت إزالة الوحدة من المفضلة','Unit removed from favorites'),'success',3500)})}}
